# Generated by Django 4.1.7 on 2023-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="공개여부"),
        ),
    ]
