# Generated by Django 4.1.7 on 2023-04-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post1',
        ),
    ]
